# Generated by Django 3.1.6 on 2021-05-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210505_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='num_quest',
            new_name='max_questions',
        ),
    ]
